version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root  # Required to install packages inside the container
    volumes:
      - /home/ubuntu/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    entrypoint: >
      bash -c "
        apt-get update &&
        apt-get install -y docker.io &&
        exec /sbin/tini -- /usr/local/bin/jenkins.sh
      "
