filebeat.inputs:
  - type: log
    paths:
      - /var/log/my-service/*.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message

output.logstash:
  hosts: ["logstash:5044"]
