name: Local Docker Build & Run

on:
  workflow_dispatch:  # trigger manually

jobs:
  build_and_run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Remove old Docker image (if exists)
        run: docker rmi -f configuration:latest || true

      - name: Build Docker image
        run: docker build -t configuration:latest .

      - name: Remove old container (if exists)
        run: docker rm -f configurationservice || true

      - name: Run Docker container
        run: |
          docker run -d \
            --name configurationservice \
            --network updated_orgadmin_rmscadminnetwork \
            -p 8082:80 \
            configuration:latest
